fic_benchmark/urls.py
from . import views
from django.urls import path

app_name = 'fic_benchmark'
urlpatterns = [
    path('', views.index, name='index'),
    path('statistics/', views.comparative_statistics, name='statistics'),#'<int:funds_id>/
    path('fund_statistics/', views.fund_statistics, name='fund_statistics'),#'<int:funds_id>/
    path('indicators/', views.indicators, name='indicators'),#'<int:funds_id>/
]

inversion_optima/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib import sitemaps
from django.contrib.sitemaps.views import sitemap
from fic_benchmark.sitemaps import StaticViewSitemap as fbs
from main.sitemaps import StaticViewSitemap as ms
sitemaps = {
    'static': fbs,
    'main': ms
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fic_benchmark.urls', namespace='fic_benchmark')),
    path('', include('main.urls', namespace='main')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

main/urls.py
from . import views
from django.urls import path

app_name = 'main'
urlpatterns = [
    path('terminos-y-condiciones/', views.terminos_y_condiciones, name='terminos-y-condiciones'),
    path('acerca-de/', views.acerca_de, name='acerca-de'),
    path('politicas-de-privacidad/', views.politicas_de_privacidad, name='politicas-de-privacidad'),
]

templates/base.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" type="image/svg" href="{% static 'images/logo.svg' %}">
    <title>{% block title %}Inversion Optima{% endblock %}</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;700&display=swap">
    <link href="https://fonts.googleapis.com/css2?family=Inconsolata:wght@400;700&display=swap" rel="stylesheet">
    <script src="{% static 'js/tabs.js' %}"></script>
    
</head>
<body>
  <header>
    <div class="header-top">
      <div class="logo" style="border-radius: 20px; border-color: antiquewhite;">
        <img src="{% static 'images/logo.svg' %}" alt="logo" width="128px">
        <h1 style="color: white;">Inversión <br>Óptima</h1>
      </div>

      <div class="header-menu">
        <div class="search">
          <input type="text" placeholder="Buscar...">
          <button>
            <img src="{% static 'images/lupa.svg' %}" alt="lupa" width="16px">
          </button>
        </div>
        <div class="user-options">
          <a href="#login">Iniciar Sesión</a>
          <a href="#register">Registrarse</a>
        </div>
      </div>
    </div>
    </header>
    <nav>
      <a href="{% url 'fic_benchmark:index' %}">Inicio</a>
      <a href="{% url 'fic_benchmark:statistics' %}">Comparativa</a>
      <a href="{% url 'fic_benchmark:indicators' %}">Indicadores</a>
      <a href="{% url 'fic_benchmark:fund_statistics' %}">Estadisticas</a>
      <a href="{% url 'main:acerca-de' %}">Acerca de</a>
      <!--  p> -- espacio -- </p -->
      <button id="dark-mode-toggle" class="split">Dark Mode</button>
    </nav>
    <script src="{% static 'js/theme_toggle.js' %}"></script>
    <script src="{% static 'js/draw_charts.js' %}"></script>
    <div id="container">
      <div id="content" style="width:90%">
        {% block container %}
        <!-- Contenido por defecto que puede ser sobrescrito -->
        {% endblock %}
      </div>
      <button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
        {% block extra_js %}{% endblock %}
    </div>
    <hr>
    <footer>
      <div class="footer-container" style="width: 90%;">
        <div class="footer-info">
          <p>&copy; 2024 Inversion Optima. Todos los derechos reservados.</p>
          <p>Contacto: <a href="mailto:{{email}}">{{email}}</a></p>
          <div class="footer-social">
            <a href="https://www.linkedin.com" target="_blank">
              <img src="{% static 'images/linkedin.svg' %}" alt="linkedin-logo" width="20px" style="align-items: center;">
            </a>
            <a href="https://www.facebook.com" target="_blank">
              <img src=" {% static 'images/facebook.svg' %}" alt="facebook-logo" width="20px" style="align-items: center;">
            </a>
            <a href="https://www.twitter.com" target="_blank">
              <img src="{% static 'images/twitter.svg' %}" alt="twitter-logo" width="20px" style="align-items: center;">
            </a>
          </div>
        </div>
        
        <div class="footer-nav">
          <ul>
            <li><a href="{% url 'main:acerca-de' %}">Acerca de</a></li>
            <li><a href="{% url 'main:terminos-y-condiciones' %}">Términos y Condiciones</a></li>
            <li><a href="{% url 'main:politicas-de-privacidad' %}">Política de Privacidad</a></li>
            <li><a href="{% url 'django.contrib.sitemaps.views.sitemap' %}">Mapa del Sitio</a></li>
          </ul>
        </div>
        
      </div>
      </footer>
      <script src="{% static 'js/scroll_to_top.js' %}"></script>
</body>
</html>