fic_benchmark/urls.py
from . import views
from django.urls import path

app_name = 'fic_benchmark'
urlpatterns = [
    path('', views.index, name='index'),
    path('statistics/', views.comparative_statistics, name='statistics'),#'<int:funds_id>/
    path('fund_statistics/', views.fund_statistics, name='fund_statistics'),#'<int:funds_id>/
    path('indicators/', views.indicators, name='indicators'),#'<int:funds_id>/
]

inversion_optima/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib import sitemaps
from django.contrib.sitemaps.views import sitemap
from fic_benchmark.sitemaps import StaticViewSitemap as fbs
from main.sitemaps import StaticViewSitemap as ms
sitemaps = {
    'static': fbs,
    'main': ms
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fic_benchmark.urls', namespace='fic_benchmark')),
    path('', include('main.urls', namespace='main')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

main/urls.py
from . import views
from django.urls import path

app_name = 'main'
urlpatterns = [
    path('terminos-y-condiciones/', views.terminos_y_condiciones, name='terminos-y-condiciones'),
    path('acerca-de/', views.acerca_de, name='acerca-de'),
    path('politicas-de-privacidad/', views.politicas_de_privacidad, name='politicas-de-privacidad'),
]

fic_benchmark/models.py
from django.db import models

# Create your models here.
class FundManager(models.Model):
    name = models.CharField(max_length=100)
    url = models.URLField(max_length=200)

    def __str__(self):
        return self.name

class Fund(models.Model):
    name = models.CharField(max_length=100)
    url = models.URLField(max_length=200)
    ticker = models.CharField(max_length=100, blank=True, null=True)
    start_of_operations = models.DateField()
    description = models.TextField()
    minimum_investment = models.FloatField(verbose_name='Minimo de inversión')
    fee = models.FloatField()
    fic_type = models.IntegerField(choices=[
        (1, 'FIC'),
        (2, 'FICI'),
        (3, 'FIC Cerrado'),
        (4, 'FIC Abierto sin pacto de permanencia'),
        (8, 'Otro')
    ])
    fund_manager = models.ForeignKey(FundManager, on_delete=models.CASCADE)
    investment_type = models.IntegerField(choices=[
        (1, 'Renta Fija'),
        (2, 'Renta Variable'),
        (3, 'Mixta RV/RF')
    ])
    risk_level = models.IntegerField(choices=[
        (1, 'Conservador'),
        (2, 'Medio'),
        (3, 'Alto Riesgo'),
        (4, 'Muy alto')
    ])
    rating = models.IntegerField(choices=[
        (1, 'AAA'),
        (2, 'AA+'),
        (3, 'AA'),
        (4, 'AA-'),
        (5, 'A+'),
        (6, 'A'),
        (7, 'A-'),
        (8, 'BBB+'),
        (9, 'BBB'),
        (10, 'BBB-'),
        (11, 'BB+'),
        (12, 'BB'),
        (13, 'BB-'),
        (14, 'B+'),
        (15, 'B'),
        (16, 'B-'),
        (17, 'CCC+'),
        (18, 'CCC'),
        (19, 'CCC-'),
        (20, 'CC'),
        (21, 'C'),
        (22, 'RD'),
        (23, 'D'),
    ])

    def get_risk_level_display(self):
        return dict(self._meta.get_field('risk_level').choices).get(self.risk_level, '')

    def get_rating_display(self):
        return dict(self._meta.get_field('rating').choices).get(self.rating, '')

    def __str__(self):
        return self.name
    
class Statistic(models.Model):
    fund = models.ForeignKey(Fund, on_delete=models.CASCADE)
    period = models.DateField()
    value_fund = models.FloatField(verbose_name='Valor del fondo en MM')
    units_in_circulation = models.FloatField(verbose_name='Unidades en circulación')
    unit_value = models.FloatField(verbose_name='Valor de la unidad')
    investors = models.PositiveIntegerField(verbose_name='Inversionistas')
    profitability = models.FloatField(verbose_name='Rentabilidad último mes en %')
    volatility = models.FloatField(verbose_name='Volatilidad último mes en %')

    def __str__(self):
        return f'{self.fund} {self.period}'
    
class Position(models.Model):
    statistic = models.ForeignKey(Statistic, on_delete=models.CASCADE, default=1)
    issuer = models.CharField(max_length=100, verbose_name='Emisor')
    participation = models.FloatField()

    def __str__(self):
        return f'{self.issuer} {self.participation} % {self.statistic.fund} {self.statistic.period}'
    
class Indicator(models.Model):
    period = models.DateField()
    inflation = models.FloatField(blank=True, null=True)
    interest_rate = models.FloatField(blank=True, null=True)
    
    def __str__(self):
        return f'{self.period} - Inflation: {self.inflation} - IBR: {self.interest_rate}'

fic_benchmark/views.py
from django.shortcuts import render, get_object_or_404
from .models import Statistic, Fund, Indicator
import json

from django.db.models import Avg, Min, Max, Sum, Count, StdDev, Variance, F, ExpressionWrapper, FloatField 

# Create your views here.
founder = "Braulio Madrid"
email = "brauliomadrid.developer@gmail.com"
def index(request):
    rating = request.GET.get('rating', '')
    risk = request.GET.get('risk', '')

    funds = Fund.objects.all()

    if rating:
        funds = funds.filter(rating=rating)

    if risk:
        funds = funds.filter(risk_level=risk)
    context = {
        'email': email,
        'funds': funds,
        'selected_rating': rating,
        'selected_risk': risk,
        'rating_choices': Fund._meta.get_field('rating').choices,
        'risk_level_choices': Fund._meta.get_field('risk_level').choices
    }
    return render(request, 'fic_benchmark/index.html', context)

def get_monthly_values(statistics, indicators):
    periods = []
    fund_values = []
    units_in_circulation = []
    unit_values = []
    investors = []
    profitability = []
    volatility = []

    units_per_investor = []
    fund_value_per_investor = []
    theoretical_fund_value = []

    profitability_diff_inflation = []
    unit_values_diff_inflation = []
    
    for stat in statistics:
        periods.append(stat.period.strftime('%Y-%m'))
        fund_values.append(round(stat.value_fund,2))
        units_in_circulation.append(round(stat.units_in_circulation,2))
        unit_values.append(round(stat.unit_value,2))
        investors.append(stat.investors)
        profitability.append(round(stat.profitability,2))
        volatility.append(round(stat.volatility,2))

        units_per_investor.append(round(stat.units_in_circulation / stat.investors,2))
        fund_value_per_investor.append(round(stat.value_fund / stat.investors,2))
        theoretical_fund_value.append(round(stat.unit_value * stat.units_in_circulation / stat.investors,2))

        matching_indicators = indicators.filter(period=stat.period)
        
        if matching_indicators.first().inflation:
            profitability_diff_inflation.append(round(stat.profitability - matching_indicators.first().inflation, 2))
        else:
            profitability_diff_inflation.append(stat.profitability)
        
        if matching_indicators.first().interest_rate:
            unit_values_diff_inflation.append(round(stat.unit_value - matching_indicators.first().interest_rate, 2))
        else:
            unit_values_diff_inflation.append(stat.unit_value)

    stats_dict = {
        'periods': periods,
        'fund_values': fund_values,
        'units_in_circulation': units_in_circulation,
        'unit_values': unit_values,
        'investors': investors,
        'profitability': profitability,
        'volatility': volatility,
        
        'units_per_investor': units_per_investor,
        'fund_value_per_investor': fund_value_per_investor,
        'theoretical_fund_value': theoretical_fund_value,

        'profitability_diff_inflation': profitability_diff_inflation,
        'unit_values_diff_inflation': unit_values_diff_inflation
    }
    return stats_dict

def get_descriptive_stats(statistics):
    aggregated_stats = statistics.aggregate(
        fund_count=Count('fund'),
        value_fund_avg=Avg('value_fund'),
        value_fund_min=Min('value_fund'),
        value_fund_max=Max('value_fund'),
        value_fund_stddev=StdDev('value_fund'),
        value_fund_variance=Variance('value_fund'),
        value_fund_sum=Sum('value_fund'),
        units_in_circulation_avg=Avg('units_in_circulation'),
        units_in_circulation_min=Min('units_in_circulation'),
        units_in_circulation_max=Max('units_in_circulation'),
        units_in_circulation_stddev=StdDev('units_in_circulation'),
        units_in_circulation_variance=Variance('units_in_circulation'),
        units_in_circulation_sum=Sum('units_in_circulation'),
        unit_value_avg=Avg('unit_value'),
        unit_value_min=Min('unit_value'),
        unit_value_max=Max('unit_value'),
        unit_value_stddev=StdDev('unit_value'),
        unit_value_variance=Variance('unit_value'),
        unit_value_sum=Sum('unit_value'),
        investors_avg=Avg('investors'),
        investors_min=Min('investors'),
        investors_max=Max('investors'),
        investors_stddev=StdDev('investors'),
        investors_variance=Variance('investors'),
        investors_sum=Sum('investors'),
        profitability_avg=Avg('profitability'),
        profitability_min=Min('profitability'),
        profitability_max=Max('profitability'),
        profitability_stddev=StdDev('profitability'),
        profitability_variance=Variance('profitability'),
        profitability_sum=Sum('profitability'),
        volatility_avg=Avg('volatility'),
        volatility_min=Min('volatility'),
        volatility_max=Max('volatility'),
        volatility_stddev=StdDev('volatility'),
        volatility_variance=Variance('volatility'),
        volatility_sum=Sum('volatility'),
    )

    rounded_stats = {
        key: round(value, 2)
        for key, value in aggregated_stats.items()
    }

    return rounded_stats

def get_filtered_statistics(funds, all_statistics, indicators, compared_fund_id):
    fund = funds.filter(id=compared_fund_id).first()
    filtered_statistics = all_statistics.filter(fund__id=compared_fund_id).order_by('period')

    descriptive_stats = {}
    if filtered_statistics.exists():
        descriptive_stats = get_descriptive_stats(filtered_statistics)

    stats_dict = get_monthly_values(filtered_statistics, indicators)

    return fund, filtered_statistics, descriptive_stats, stats_dict

def get_comparative_statistics(fund_id, compare_fund_id):
    funds = Fund.objects.all()
    all_statistics = Statistic.objects.all()
    indicators = Indicator.objects.all().order_by('period')

    selected_fund, filtered_statistics, filtered_stats, values = get_filtered_statistics(funds, all_statistics, indicators, fund_id)
    compared_fund, compared_filtered_statistics, compared_stats, compared_values = get_filtered_statistics(funds, all_statistics, indicators, compare_fund_id)

    context = {
        'email': email,
        'funds': funds,
        'selected_fund': selected_fund,
        'filtered_statistics': filtered_statistics,
        'filtered_stats': filtered_stats,
        'filtered_stats_json': json.dumps(filtered_stats),
        'values': json.dumps(values),
        'compared_fund': compared_fund,
        'compared_filtered_statistics': compared_filtered_statistics,
        'compared_stats': compared_stats,
        'compared_values': json.dumps(compared_values),
    }
    return context

def get_statistics(fund_id):
    funds = Fund.objects.all()
    all_statistics = Statistic.objects.all()
    indicators = Indicator.objects.all().order_by('period')

    selected_fund, filtered_statistics, filtered_stats, values = get_filtered_statistics(funds, all_statistics, indicators, fund_id)

    context = {
        'email': email,
        'funds': funds,
        'selected_fund': selected_fund,
        'filtered_statistics': filtered_statistics,
        'filtered_stats': filtered_stats,
        'filtered_stats_json': json.dumps(filtered_stats),
        'values': json.dumps(values),
    }
    return context

def dates_list_to_string(dates_list):
    return [str(date) for date in dates_list]

def comparative_statistics(request):
    fund_id = request.GET.get('fund_id', request.GET.get('fund.id', None))
    compare_fund_id = request.GET.get('compare_fund_id', request.GET.get('compare_fund.id', None))
    context = get_comparative_statistics(fund_id, compare_fund_id)
    return render(request, 'fic_benchmark/statistics.html', context)

def fund_statistics(request):
    fund_id = request.GET.get('fund_id', request.GET.get('fund.id', None))
    context = get_statistics(fund_id)
    return render(request, 'fic_benchmark/fund_statistics.html', context)

def calculate_statistics(data, stats_func):
    return round(stats_func(data), 2) if len(data) > 0 else 0

def indicators(request):
    indicators = Indicator.objects.all().order_by('period')

    inflation_stats = indicators.aggregate(
        avg_inflation=Avg('inflation'),
        min_inflation=Min('inflation'),
        max_inflation=Max('inflation'),
        std_inflation=StdDev('inflation'),
        variance_inflation=Variance('inflation'),
        sum_inflation=Sum('inflation'),
        count_inflation=Count('inflation')
    )

    interest_rate_stats = indicators.aggregate(
        avg_interest_rate=Avg('interest_rate'),
        min_interest_rate=Min('interest_rate'),
        max_interest_rate=Max('interest_rate'),
        std_interest_rate=StdDev('interest_rate'),
        variance_interest_rate=Variance('interest_rate'),
        sum_interest_rate=Sum('interest_rate'),
        count_interest_rate=Count('interest_rate')
    )

    inflation_stats = {key: round(value, 2) for key, value in inflation_stats.items()}
    interest_rate_stats = {key: round(value, 2) for key, value in interest_rate_stats.items()}

    indicators_periods = list(indicators.values_list('period', flat=True))
    indicators_dict = {
        'periods': dates_list_to_string(indicators_periods),
        'inflation': list(indicators.values_list('inflation', flat=True)),
        'interest_rate': list(indicators.values_list('interest_rate', flat=True))
    }

    context = {
        'email': email,
        'indicators': indicators,
        'inflation_stats': inflation_stats,
        'interest_rate_stats': interest_rate_stats,
        'indicators_dict': json.dumps(indicators_dict),
    }

    return render(request, 'fic_benchmark/indicators.html', context)

fic_benchmark/templates/fic_benchmark/base.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'fic_benchmark/style.css' %}">
    <link rel="icon" type="image/svg" href="{% static 'fic_benchmark/logo.svg' %}">
    <title>{% block title %}Inversion Optima{% endblock %}</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;700&display=swap">
    <link href="https://fonts.googleapis.com/css2?family=Inconsolata:wght@400;700&display=swap" rel="stylesheet">
    <script src="{% static 'fic_benchmark/tabs.js' %}"></script>
    
</head>
<body>
  <header>
    <div class="header-top">
      <div class="logo" style="border-radius: 20px; border-color: antiquewhite;">
        <img src="{% static 'fic_benchmark/logo.svg' %}" alt="logo" width="128px">
        <h1 style="color: white;">Inversión <br>Óptima</h1>
      </div>

      <div class="header-menu">
        <div class="search">
          <input type="text" placeholder="Buscar...">
          <button>
            <img src="{% static 'fic_benchmark/lupa.svg' %}" alt="lupa" width="16px">
          </button>
        </div>
        <div class="user-options">
          <a href="#login">Iniciar Sesión</a>
          <a href="#register">Registrarse</a>
        </div>
      </div>
    </div>
    </header>
    <nav>
      <a href="{% url 'fic_benchmark:index' %}">Inicio</a>
      <a href="{% url 'fic_benchmark:statistics' %}">Comparativa</a>
      <a href="{% url 'fic_benchmark:indicators' %}">Indicadores</a>
      <a href="{% url 'fic_benchmark:fund_statistics' %}">Estadisticas</a>
      <a href="{% url 'fic_benchmark:acerca-de' %}">Acerca de</a>
      <!--  p> -- espacio -- </p -->
      <button id="dark-mode-toggle" class="split">Dark Mode</button>
    </nav>
    <script src="{% static 'fic_benchmark/theme_toggle.js' %}"></script>
    <script src="{% static 'fic_benchmark/draw_charts.js' %}"></script>
    <div id="container">
      <div id="content" style="width:90%">
        {% block container %}
        <!-- Contenido por defecto que puede ser sobrescrito -->
        {% endblock %}
      </div>
      <button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
        {% block extra_js %}{% endblock %}
    </div>
    <hr>
    <footer>
      <div class="footer-container" style="width: 90%;">
        <div class="footer-info">
          <p>&copy; 2024 Inversion Optima. Todos los derechos reservados.</p>
          <p>Contacto: <a href="mailto:{{email}}">{{email}}</a></p>
          <div class="footer-social">
            <a href="https://www.linkedin.com" target="_blank">
              <img src="{% static 'fic_benchmark/linkedin.svg' %}" alt="linkedin-logo" width="20px" style="align-items: center;">
            </a>
            <a href="https://www.facebook.com" target="_blank">
              <img src=" {% static 'fic_benchmark/facebook.svg' %}" alt="facebook-logo" width="20px" style="align-items: center;">
            </a>
            <a href="https://www.twitter.com" target="_blank">
              <img src="{% static 'fic_benchmark/twitter.svg' %}" alt="twitter-logo" width="20px" style="align-items: center;">
            </a>
          </div>
        </div>
        
        <div class="footer-nav">
          <ul>
            <li><a href="{% url 'fic_benchmark:acerca-de' %}">Acerca de</a></li>
            <li><a href="{% url 'fic_benchmark:terminos-y-condiciones' %}">Términos y Condiciones</a></li>
            <li><a href="{% url 'fic_benchmark:politicas-de-privacidad' %}">Política de Privacidad</a></li>
            <li><a href="{% url 'django.contrib.sitemaps.views.sitemap' %}">Mapa del Sitio</a></li>
          </ul>
        </div>
        
      </div>
      </footer>
      <script src="{% static 'fic_benchmark/scroll_to_top.js' %}"></script>
</body>
</html>

fic_benchmark/templates/fic_benchmark/index.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block title %}Inversion Optima{% endblock %}
{% block container %}

<h1>Qué es Inversión Óptima</h1>
<p>Inversión Óptima es una plataforma dedicada a medir y analizar el rendimiento de varios fondos de inversión colectiva. Nuestro objetivo es proporcionar a los inversionistas la información y las herramientas necesarias para tomar decisiones informadas y maximizar sus retornos.</p>
<h2>Todos los fondos</h2>
<p>Por favor, seleccione una de las siguientes opciones:</p>
<p>Todos los fondos: <b>{{funds.count}}</b></p>
<form method="GET">
<label for="rating">Calificación:</label>
<select name="rating" id="rating">
    <option value="">Todos</option>
    {% for value, display in rating_choices %}
        <option value="{{ value }}" {% if selected_rating == value|stringformat:"s" %}selected{% endif %}>{{ display }}</option>
    {% endfor %}
</select>
   
<label for="risk">Riesgo:</label>
    <select name="risk" id="risk">
        <option value="">Todos</option>
        {% for value, display in risk_level_choices %}
             <option value="{{ value }}" {% if selected_risk == value|stringformat:"s" %}selected{% endif %}>{{ display }}</option>
        {% endfor %}
    </select>

   <button type="submit">Filtrar</button>
</form>
   
<section>
    {% for fund in funds %}
        <!-- Aquí va tu código actual para mostrar los fondos -->
         <details>
             <summary><b>{{fund.name}}</b> - Riesgo: <b>{{fund.get_risk_level_display}}</b> Calificación: <b>{{fund.get_rating_display}}</b></summary>
             <p>{{fund.description}}</p>
             <p>Minimo de inversión: $<b>{{fund.minimum_investment|intcomma}}</b> comisión: <b>{{fund.fee}}</b> % <br>
             <b>{{fund.get_fic_type_display}}</b> Tipo de inversión: <b>{{fund.get_investment_type_display}}</b>
             </p>
             <a href="{{fund.url}}">web del fondo</a>
             <a href="{% url 'fic_benchmark:fund_statistics' %}?fund_id={{fund.id}}">estadisticas</a>
         </details>
    {% endfor %}
</section>
    
<script>
    var choices = '{{ choice|escapejs }}';
    console.log(choices);
</script>

{% endblock %}

fic_benchmark/templates/fic_benchmark/indicators.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block title %}Indicadores{% endblock %}

{% block container %}
<h2>Indicadores</h2>
<p>Por favor, seleccione una de las siguientes opciones:</p>

<section>
    <details>
        <summary>Inflacion y tasa de interés</b></summary>
        <table>
            <tr>
                <th>Periodo</th>
                <th>Inflación</th>
                <th>Tasa de interés</th>
            </tr>
            {% for indicator in indicators %}
                <tr>
                    <td class="text-right">{{ indicator.period|date:"M Y" }}</td>
                    <td class="text-right">{{ indicator.inflation }} %</td>
                    <td class="text-right">{{ indicator.interest_rate }} %</td>
                </tr>
            {% endfor %}
        </table>
        <table>
            <tr>
                <th>Dato</th>
                <th>Conteo</th>
                <th>Mínimo</th>
                <th>Media</th>
                <th>Máximo</th>
                <th>Desviación std</th>
                <th>Varianza</th>
                <th>Sumatoria</th>
            </tr>
            <tr>
                <td class="text-right"><b>Inflación: </b></td>
                <td class="text-right">{{ indicators.count }}</td>
                <td class="text-right">{{ inflation_stats.min_inflation|intcomma }} %</td>
                <td class="text-right">{{ inflation_stats.avg_inflation|intcomma }} %</td>
                <td class="text-right">{{ inflation_stats.max_inflation|intcomma }} %</td>
                <td class="text-right">{{ inflation_stats.std_inflation|intcomma }} %</td>
                <td class="text-right">{{ inflation_stats.variance_inflation|intcomma }} %</td>
                <td class="text-right">{{ inflation_stats.sum_inflation|intcomma }} %</td>
            </tr>
            <tr>
                <td class="text-right"><b>Tasa de interés: </b></td>
                <td class="text-right">{{ indicators.count }}</td>
                <td class="text-right">{{ interest_rate_stats.min_interest_rate|intcomma }} %</td>
                <td class="text-right">{{ interest_rate_stats.avg_interest_rate|intcomma }} %</td>
                <td class="text-right">{{ interest_rate_stats.max_interest_rate|intcomma }} %</td>
                <td class="text-right">{{ interest_rate_stats.std_interest_rate|intcomma }} %</td>
                <td class="text-right">{{ interest_rate_stats.variance_interest_rate|intcomma }} %</td>
                <td class="text-right">{{ interest_rate_stats.sum_interest_rate|intcomma }} %</td>
            </tr>
        </table>

    </details>
</section>
<script>
    let indicators_dict = JSON.parse('{{ indicators_dict|safe|escapejs }}')
    console.log("Descriptive Inflation: " + indicators_dict.descriptive_inflation)
    console.log("Descriptive Interest Rate: " + indicators_dict.descriptive_interest_rate)
</script>
<canvas id="inflation_interest_rates" width="400" height="200"></canvas>
<script src="{% static 'fic_benchmark/indicators_charts.js' %}"></script>
{% endblock %}